-- MySQL Script generated by MySQL Workbench
-- Fri May  6 09:29:07 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `checkpoint2` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema checkpoint2
-- -----------------------------------------------------
USE `checkpoint2` ;

-- -----------------------------------------------------
-- Table `mydb`.`accessory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `checkpoint2`.`accessory` (
  `category_id` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  `url` VARCHAR(255) NULL,
  PRIMARY KEY (`category_id`));


-- -----------------------------------------------------
-- Table `mydb`.`cupcake`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `checkpoint2`.`cupcake` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  `color1` VARCHAR(7) NULL,
  `color2` VARCHAR(7) NULL,
  `color3` VARCHAR(7) NULL,
  `accessory_id` INT NULL,
  `created_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cupcake_accessory_idx` (`accessory_id` ASC) VISIBLE,
  CONSTRAINT `fk_cupcake_accessory`
    FOREIGN KEY (`accessory_id`)
    REFERENCES `checkpoint2`.`accessory` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
